version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm install serverless -g
  build:
    #         aws cloudfront create-invalidation --distribution-id $CLOUDFRONTID --paths '/*';
    commands:
      - npm install
      - npm run build
      - if [ $CODEBUILD_BUILD_SUCCEEDING = 1 ]; then
        serverless deploy;
        else
        echo build failed;
        fi
