version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - yarn global add gatsby@latest
  pre_build:
    commands:
      - yarn install --frozen-lockfile
  build:
    commands:
      - CI=true yarn build
      # - "yarn test:e2e:ci"
  post_build:
    commands:
      - yarn deploy
artifacts:
  base-directory: public
  files:
    - "**/*"
  discard-paths: no
# cache:
#   paths:
#     - ".cache/*"
#     - "public/*"
