# version: 0.2
# phases:
#   install:
#     runtime-versions:
#       nodejs: 10
#     commands:
#       - echo Installing Gatsby and Gatsby-CLI...
#       - npm install -g gatsby
#       # - npm install -g gatsby-cli --force
#     pre_build:
#       commands:
#         - yarn install
#     build:
#       commands:
#         - echo Build initiated...
#         - GATSBY_ACTIVE_ENV=$ENVIRONMENT S3_BUCKET=$S3_BUCKET yarn build
#     post_build:
#       commands:
#         - echo Synchronizing public directory...
#         - if [ $CODEBUILD_BUILD_SUCCEEDING = 1 ]; then
#           GATSBY_ACTIVE_ENV=$ENVIRONMENT S3_BUCKET=$S3_BUCKET yarn deploy;
#           else
#           echo Build failed ignoring deployment;
#           fi
# artifacts:
#   base-directory: public
#   files:
#     - "**/*"
#   discard-paths: yes
version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - "touch .npmignore"
      - "npm install -g gatsby"
  pre_build:
    commands:
      - "yarn install --frozen-lockfile"
  build:
    commands:
      - "yarn build"
  post_build:
    commands:
      - "yarn deploy"
artifacts:
  base-directory: public
  files:
    - "**/*"
  discard-paths: no
cache:
  paths:
    - ".cache/*"
    - "public/*"
