version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - "touch .npmignore"
      - "npm install -g gatsby"
      # Install Cypress dependencies
      - apt-get update
      - apt-get install -y libgtk2.0-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 xvfb
  pre_build:
    commands:
      - "yarn install --frozen-lockfile"
  build:
    commands:
      - printenv > .env
      - "yarn build"
      - "yarn test:e2e:ci"
  post_build:
    commands:
      - "yarn deploy"
artifacts:
  base-directory: public
  files:
    - "**/*"
  discard-paths: no
cache:
  paths:
    - ".cache/*"
    - "public/*"
