name: Linting Formatting Unit and Integration Tests

on:
  pull_request:
    branches:
      - "main"

jobs:
  validate-code-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12.x]
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node: ${{ matrix.node }}
      - name: Install Dependencies
        run: |
          yarn install --non-interactive
      - name: Run Prettier
        run: |
          yarn format
      - name: Run Lint
        run: |
          yarn lint
      # - name: Run Unit and Integration tests
      #   run: |
      #     yarn jest
